services:
  - type: web
    name: medical-core-api
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://${MYSQL_HOST}:3306/medical_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: ${MYSQL_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${MYSQL_PASSWORD}
      - key: KEYCLOAK_AUTH_SERVER_URL
        value: ${KEYCLOAK_URL}
      - key: KEYCLOAK_REALM
        value: medical-realm
      - key: KEYCLOAK_RESOURCE
        value: medical-client
      - key: KEYCLOAK_CREDENTIALS_SECRET
        value: ${KEYCLOAK_CLIENT_SECRET}
      - key: KEYCLOAK_PUBLIC_CLIENT
        value: "false"
      - key: KEYCLOAK_PRINCIPAL_ATTRIBUTE
        value: admin
      - key: KEYCLOAK_ADMIN_USERNAME
        value: ${KEYCLOAK_ADMIN}
      - key: KEYCLOAK_ADMIN_PASSWORD
        value: ${KEYCLOAK_PASSWORD}
      - key: KEYCLOAK_ADMIN_CLIENT_ID
        value: admin-cli
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    healthCheckPath: /actuator/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1

databases:
  - name: medical-db
    databaseName: medical_db
    plan: free
    ipAllowList: [] 